<h1 style="color:rgb(0, 0, 0);">Pytorch Lesson-2</h1> 

<h3 style="color:rgb(0, 0, 255);">Math functions with tensor</h3> 

<a href="https://pytorch.org/docs/stable/torch.html">
    more functions </a>

<img src="images/pytorch.jpg" style="width:400px;height:200px">

<h3 style="color:rgb(0, 0, 0);">Functions:</h3>

* torch.rand()
* torch.randn()
* torch.randint()
* torch.zeros()
* torch.ones()
* torch.eye()
* torch.numel()
* torch.exp()
* torch.mean()
* torch.std()
* torch.cumsum()
* torch.view()
* torch.reshape()
* torch.add()
* torch.sub()
* torch.mul()
* torch.div()


<p> <i> Good Luck !!! &#128525;</i> </p> 


In [1]:
import torch

In [2]:
x = torch.rand(5, 5, dtype=torch.float32) 
# default dtype=torch.float32
print(x)
print(type(x))
print(x.dtype)

tensor([[0.3482, 0.0570, 0.8897, 0.9221, 0.3030],
        [0.8473, 0.1765, 0.2533, 0.2288, 0.1250],
        [0.2152, 0.8081, 0.6199, 0.8457, 0.7601],
        [0.1309, 0.6831, 0.4846, 0.8295, 0.1366],
        [0.2913, 0.4065, 0.3479, 0.6861, 0.7728]])
<class 'torch.Tensor'>
torch.float32


In [3]:
x = torch.randn(5, 5, dtype=torch.float32) 
# default dtype=torch.float32
print(x)
print(type(x))
print(x.dtype)

tensor([[ 0.2809, -1.2618,  0.2254, -0.2534, -2.1605],
        [-0.3782,  1.2336,  0.9535, -1.1543,  0.3770],
        [ 0.4740, -0.5817, -0.7121,  0.1988, -0.8559],
        [-0.2750, -2.7761, -2.6687, -0.7534,  0.1569],
        [-1.1227,  0.0295,  0.5306,  0.7203,  1.5785]])
<class 'torch.Tensor'>
torch.float32


In [4]:
x = torch.randint(5,10,(5,5), dtype=torch.float32) # low,high,(size)
y = torch.randint(100,(5,5), dtype=torch.float32) 
# default dtype=torch.float32
print(x)
print(y)

tensor([[8., 8., 5., 7., 8.],
        [8., 7., 5., 6., 6.],
        [7., 7., 9., 5., 8.],
        [6., 5., 9., 5., 8.],
        [6., 7., 5., 7., 8.]])
tensor([[59.,  9., 39., 38., 72.],
        [66., 33., 82., 67., 78.],
        [99., 83., 39., 35., 51.],
        [28., 14., 49.,  7., 16.],
        [24., 15., 36., 55.,  8.]])


In [5]:
x = torch.randperm(10)
print(x)

tensor([7, 4, 8, 3, 5, 6, 2, 0, 1, 9])


In [6]:
x = torch.zeros(3, 3)
print(x)
print(x.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [7]:
x = torch.ones(3, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [8]:
x = torch.eye(3, 3)
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [9]:
torch.numel(x)

9

In [10]:
x.dtype

torch.float32

In [11]:
x.device

device(type='cpu')

In [12]:
x.requires_grad # If autograd should record operations on the returned tensor.

False

In [13]:
x.to('cuda:0')

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], device='cuda:0')

In [14]:
x = torch.randint(2,10,(2,2))
print(x)

tensor([[8, 8],
        [6, 6]])


In [15]:
torch.exp(x.float())

tensor([[2980.9580, 2980.9580],
        [ 403.4288,  403.4288]])

In [16]:
torch.mean(x.float(),axis=1)

tensor([8., 6.])

In [17]:
torch.mean(x.float(),axis=0)

tensor([7., 7.])

In [18]:
torch.std(x.float(),axis=0)

tensor([1.4142, 1.4142])

In [19]:
x = torch.randperm(10)
print(x)
torch.cumsum(x, dim=0)

tensor([0, 5, 2, 9, 6, 1, 7, 3, 8, 4])


tensor([ 0,  5,  7, 16, 22, 23, 30, 33, 41, 45])

In [20]:
x = torch.randint(3,40,(2,2))
print(x)
torch.cumsum(x, dim=0)

tensor([[13, 20],
        [39,  9]])


tensor([[13, 20],
        [52, 29]])

In [21]:
x = torch.randint(3,40,(4,4))
x.size()

torch.Size([4, 4])

In [22]:
x.view(8,2)

tensor([[27, 25],
        [33, 34],
        [20, 13],
        [32, 34],
        [29, 32],
        [14, 19],
        [13, 26],
        [36, 18]])

In [23]:
x.view(-1)

tensor([27, 25, 33, 34, 20, 13, 32, 34, 29, 32, 14, 19, 13, 26, 36, 18])

In [24]:
x.view(2,8) #share

tensor([[27, 25, 33, 34, 20, 13, 32, 34],
        [29, 32, 14, 19, 13, 26, 36, 18]])

In [25]:
x.view(2,8) #share or copy

tensor([[27, 25, 33, 34, 20, 13, 32, 34],
        [29, 32, 14, 19, 13, 26, 36, 18]])

In [26]:
x = torch.randint(3,40,(2,2))
y = torch.randint(3,40,(2,2))
print(x)
print(y)

tensor([[19, 17],
        [19, 13]])
tensor([[27, 15],
        [10, 22]])


In [27]:
print(torch.add(x,y))
print(x.add(y))

tensor([[46, 32],
        [29, 35]])
tensor([[46, 32],
        [29, 35]])


In [28]:
print(torch.sub(x,y))
print(torch.mul(x,y))
print(torch.div(x.float(),y.float()))

tensor([[-8,  2],
        [ 9, -9]])
tensor([[513, 255],
        [190, 286]])
tensor([[0.7037, 1.1333],
        [1.9000, 0.5909]])


In [29]:
x = torch.randint(3,40,(2,2))
print(x)
print(x.add(y))
print(x)

tensor([[35, 25],
        [39, 35]])
tensor([[62, 40],
        [49, 57]])
tensor([[35, 25],
        [39, 35]])


In [30]:
x = torch.randint(3,40,(2,2))
print(x)
print(x.add_(y))
print(x)

tensor([[33, 10],
        [33, 17]])
tensor([[60, 25],
        [43, 39]])
tensor([[60, 25],
        [43, 39]])
