<h1 style="color:rgb(0, 0, 0);">Pytorch Lesson-3</h1> 

<h3 style="color:rgb(0, 0, 255);">   
  <ol>
      <li>Convert tensor-numpy-python list</li>
      <li>Variable copy-share</li>
      <li>Change cpu-cuda</li>
    </ol>
</h3>

<img src="images/pytorch.jpg" style="width:400px;height:200px">

We will learn the following:

* from numpy to tensor
* variable copy-share
* change cpu-cuda
* from python list to tensor
* from tensor to get a python list or number
* from tensor to numpy
* convert respectively (tensor cuda - numpy - python list)

<h3 style="color:rgb(0, 0, 0);">Functions:</h3>

* torch.from_numpy()
* x.copy()
* torch.cuda.is_available()
* x.to('cuda:0')
* x.to('cpu')
* x.tolist()
* x.numpy()
* x.item()
* torch.tensor([])
* torch.FloatTensor([])
* torch.as_tensor([])
* np.array([])

<p> <i> Good Luck !!! &#128525;</i> </p> 


In [1]:
import numpy as np
import torch

### from numpy to tensor

In [2]:
x = np.array([[1,2,3,4], [2,3,4,5],
              [4,5,6,7], [5,6,7,8]], dtype=np.float32)
print(x)
x.dtype

[[1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [4. 5. 6. 7.]
 [5. 6. 7. 8.]]


dtype('float32')

In [3]:
y = torch.from_numpy(x) # share
print(y)
y.dtype

tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.],
        [4., 5., 6., 7.],
        [5., 6., 7., 8.]])


torch.float32

### variable copy-share 

In [4]:
x[2,2]=99 # change x variable
print(x)
print(y) # y is changing

[[ 1.  2.  3.  4.]
 [ 2.  3.  4.  5.]
 [ 4.  5. 99.  7.]
 [ 5.  6.  7.  8.]]
tensor([[ 1.,  2.,  3.,  4.],
        [ 2.,  3.,  4.,  5.],
        [ 4.,  5., 99.,  7.],
        [ 5.,  6.,  7.,  8.]])


In [5]:
y = torch.from_numpy(x.copy()) # copy
print(y)
y.dtype

tensor([[ 1.,  2.,  3.,  4.],
        [ 2.,  3.,  4.,  5.],
        [ 4.,  5., 99.,  7.],
        [ 5.,  6.,  7.,  8.]])


torch.float32

In [6]:
x[2,2] = 88 # change x variable
print(x)
print(y) # y is not changing

[[ 1.  2.  3.  4.]
 [ 2.  3.  4.  5.]
 [ 4.  5. 88.  7.]
 [ 5.  6.  7.  8.]]
tensor([[ 1.,  2.,  3.,  4.],
        [ 2.,  3.,  4.,  5.],
        [ 4.,  5., 99.,  7.],
        [ 5.,  6.,  7.,  8.]])


### change cpu-cuda

In [7]:
# device config
check_device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("check device = " + str(check_device))

check device = cuda


In [8]:
print(y)
y.device

tensor([[ 1.,  2.,  3.,  4.],
        [ 2.,  3.,  4.,  5.],
        [ 4.,  5., 99.,  7.],
        [ 5.,  6.,  7.,  8.]])


device(type='cpu')

In [9]:
z = y.to('cuda:0')
z

tensor([[ 1.,  2.,  3.,  4.],
        [ 2.,  3.,  4.,  5.],
        [ 4.,  5., 99.,  7.],
        [ 5.,  6.,  7.,  8.]], device='cuda:0')

In [10]:
y[1,1]=100
y

tensor([[  1.,   2.,   3.,   4.],
        [  2., 100.,   4.,   5.],
        [  4.,   5.,  99.,   7.],
        [  5.,   6.,   7.,   8.]])

In [11]:
z

tensor([[ 1.,  2.,  3.,  4.],
        [ 2.,  3.,  4.,  5.],
        [ 4.,  5., 99.,  7.],
        [ 5.,  6.,  7.,  8.]], device='cuda:0')

In [12]:
c = z.to('cpu')
print(c)
c.device

tensor([[ 1.,  2.,  3.,  4.],
        [ 2.,  3.,  4.,  5.],
        [ 4.,  5., 99.,  7.],
        [ 5.,  6.,  7.,  8.]])


device(type='cpu')

### from python list to tensor

In [13]:
python_list = [[1.,2.,3.,4.],[5.,6.,7.,8.],[9.,10.,11.,12.]]
print(python_list)
type(python_list)

[[1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0], [9.0, 10.0, 11.0, 12.0]]


list

In [14]:
w1 = torch.FloatTensor(python_list)
w2 = torch.tensor(python_list)
w3 = torch.as_tensor(python_list)
print(w1)
print(w2)
print(w3)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [15]:
python_list[0][0] = 99
print(python_list)
print(w1)
print(w2)
print(w3)

[[99, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0], [9.0, 10.0, 11.0, 12.0]]
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


### from tensor to get a python list or number

In [16]:
x = torch.tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.],
        [4., 5., 6., 7.],
        [5., 6., 7., 8.]])
print(x)
print(x.tolist())

tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.],
        [4., 5., 6., 7.],
        [5., 6., 7., 8.]])
[[1.0, 2.0, 3.0, 4.0], [2.0, 3.0, 4.0, 5.0], [4.0, 5.0, 6.0, 7.0], [5.0, 6.0, 7.0, 8.0]]


In [17]:
print(x[0][0])
print(x[0][0].item())

tensor(1.)
1.0


In [18]:
x = x.to('cuda:0')
print(x.tolist())
print(x[0][0].item())

[[1.0, 2.0, 3.0, 4.0], [2.0, 3.0, 4.0, 5.0], [4.0, 5.0, 6.0, 7.0], [5.0, 6.0, 7.0, 8.0]]
1.0


### from tensor to numpy

In [19]:
x = torch.tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.],
        [4., 5., 6., 7.],
        [5., 6., 7., 8.]])
x

tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.],
        [4., 5., 6., 7.],
        [5., 6., 7., 8.]])

In [20]:
y = x.numpy()  # share
z = x.numpy().copy()  # copy
print(y)
print(z)

[[1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [4. 5. 6. 7.]
 [5. 6. 7. 8.]]
[[1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [4. 5. 6. 7.]
 [5. 6. 7. 8.]]


In [21]:
x[0][0]=99
print(y)
print(z)

[[99.  2.  3.  4.]
 [ 2.  3.  4.  5.]
 [ 4.  5.  6.  7.]
 [ 5.  6.  7.  8.]]
[[1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [4. 5. 6. 7.]
 [5. 6. 7. 8.]]


In [22]:
a = torch.tensor(0.1).numpy()
a

array(0.1, dtype=float32)

In [23]:
b = torch.tensor(0.1).to('cuda:0').to('cpu').numpy()
b

array(0.1, dtype=float32)

In [24]:
torch.tensor(0.1).to('cuda:0').item()

0.10000000149011612

### convert respectively (tensor cuda - numpy - python list)

In [25]:
x = torch.tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.],
        [4., 5., 6., 7.],
        [5., 6., 7., 8.]],device='cuda')
print(x)

tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.],
        [4., 5., 6., 7.],
        [5., 6., 7., 8.]], device='cuda:0')


In [26]:
y = x.to('cpu').numpy().tolist()
y

[[1.0, 2.0, 3.0, 4.0],
 [2.0, 3.0, 4.0, 5.0],
 [4.0, 5.0, 6.0, 7.0],
 [5.0, 6.0, 7.0, 8.0]]

In [27]:
z = x[0,0].to('cpu').numpy().item()
print(z)
type(z)

1.0


float