<h1 style="color:rgb(0, 0, 0);">Pytorch Lesson-1</h1> 

<h3 style="color:rgb(0, 0, 255);">What is tensor?</h3> 

<img src="images/pytorch.jpg" style="width:400px;height:200px">

We will learn the following definitions:

* <h3 style="color:rgb(255, 0, 0); font-size:125%;"  >Scalar</h3> 

    In linear algebra, real numbers are called scalars.

* <h3 style="color:rgb(255, 0, 0); font-size:125%;">Vector</h3> 

    A vector is a one-dimensional or first order tensor.

* <h3 style="color:rgb(255, 0, 0); font-size:125%;">Matrix</h3> 

    A matrix is a two-dimensional or second order tensor.

* <h3 style="color:rgb(255, 0, 0); font-size:125%;">Tensor</h3> 

    A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array. 


<p> <i> Good Luck !!! &#128525;</i> </p> 


### Python

In [1]:
scalar = 2
print(scalar)
print(type(scalar))

2
<class 'int'>


In [2]:
vector = [1,2,3]
print(vector)
print(type(vector))

[1, 2, 3]
<class 'list'>


In [3]:
matrix = [[1,2,3],
          [4,5,6],
          [7,8,9]]
print(matrix)
print(type(matrix))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>


In [4]:
tensor = [
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ]
print(tensor)
print(type(tensor))
tensor[0][0][0]

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[11, 12, 13], [14, 15, 16], [17, 18, 19]], [[21, 22, 23], [24, 25, 26], [27, 28, 29]]]
<class 'list'>


1

### Numpy

In [5]:
import numpy as np
numpy_scalar = np.array(1)
print(numpy_scalar)
print(type(numpy_scalar))
print(numpy_scalar.shape)

1
<class 'numpy.ndarray'>
()


In [6]:
numpy_vector = np.array([1, 2, 3])
print(numpy_vector)
print(type(numpy_vector))
print(numpy_vector.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [7]:
numpy_matrix = np.array([[1,2,3],
                         [4,5,6],
                         [7,8,9]])
print(numpy_matrix)
print(type(numpy_matrix))
print(numpy_matrix.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)


In [8]:
numpy_tensor = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
print(numpy_tensor)
print(type(numpy_tensor))
print(numpy_tensor.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
<class 'numpy.ndarray'>
(3, 3, 3)


### Pytorch

In [10]:
import torch
tensor = torch.tensor([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
print(tensor)
print(type(tensor))
print(tensor.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]],

        [[21, 22, 23],
         [24, 25, 26],
         [27, 28, 29]]])
<class 'torch.Tensor'>
torch.Size([3, 3, 3])


## input image data for training model 
image data shape = [batch_size, channel, height, width] 
                 
                  = [8 3 224 224]